/**
 * 错误码常量
 */

export const ERROR_CODES = {
  // 通用错误
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  NETWORK_ERROR: "NETWORK_ERROR",
  TIMEOUT_ERROR: "TIMEOUT_ERROR",

  // 命令相关错误
  COMMAND_NOT_FOUND: "COMMAND_NOT_FOUND",
  COMMAND_ALREADY_RUNNING: "COMMAND_ALREADY_RUNNING",
  COMMAND_EXECUTION_FAILED: "COMMAND_EXECUTION_FAILED",
  COMMAND_VALIDATION_FAILED: "COMMAND_VALIDATION_FAILED",

  // 数据库相关错误
  DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
  DATABASE_QUERY_FAILED: "DATABASE_QUERY_FAILED",
  DATABASE_WRITE_FAILED: "DATABASE_WRITE_FAILED",

  // 配置相关错误
  CONFIG_LOAD_FAILED: "CONFIG_LOAD_FAILED",
  CONFIG_SAVE_FAILED: "CONFIG_SAVE_FAILED",

  // 文件相关错误
  FILE_READ_FAILED: "FILE_READ_FAILED",
  FILE_WRITE_FAILED: "FILE_WRITE_FAILED",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",

  // 系统相关错误
  AUTOSTART_ENABLE_FAILED: "AUTOSTART_ENABLE_FAILED",
  AUTOSTART_DISABLE_FAILED: "AUTOSTART_DISABLE_FAILED",
} as const;

/**
 * 错误码类型
 */
export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

